config/routes.rb
Rails.application.routes.draw do
 
  resources :owners

  get 'cats/search', to: 'cats#search'
  delete 'cats/:id/image', to: 'cats#delete_image', as: 'delete_cat_image'
  
  resources :cats

  root 'home#index'

end

app/models/cat.rb
class Cat < ActiveRecord::Base
  belongs_to :owner
  validates :name, presence: true
  validates :birth_date, presence: { :message => "Should be a date"}

  mount_uploader :picture, CatPictureUploader

end

app/models/owner.rb
class Owner < ActiveRecord::Base
  has_many :cats, dependent: :destroy
  accepts_nested_attributes_for :cats, :reject_if => lambda { |c| c[:name].blank? }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_filter :find_cat, only: [:show, :destroy, :delete_image]
  def index
    @cats = Cat.all
  end

  def show
  end

  def search
    search_term = params[:name] 
    if search_term != "" || search_term.nil?
      @cats = Cat.where(['name LIKE ?', "%#{search_term}%"])  
      
    else
      @cats = []

    end
  end

  def new
    @cat = Cat.new
  end

  def create
    @cat = Cat.new(cat_params)

    if @cat.save
      redirect_to cats_path
    else
      render :new
    end
  end

  def destroy
    @cat.destroy
    redirect_to cats_path
  end

  def delete_image
    @cat.remove_picture!
    @cat.save
    redirect_to :back
  end

  private
  def cat_params
    params.require(:cat).permit(:name, :birth_date, :picture)
  end

  def find_cat
    @cat = Cat.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @cats = Cat.all
  end
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  before_action :set_owner, only: [:show, :edit, :update, :destroy]

  # GET /owners
  # GET /owners.json
  def index
    @owners = Owner.all
  end

  # GET /owners/1
  # GET /owners/1.json
  def show
  end

  # GET /owners/new
  def new
    @owner = Owner.new
    @owner.cats.build 
  end

  # GET /owners/1/edit
  def edit
    @owner.cats.build
  end

  # POST /owners
  # POST /owners.json
  def create
    @owner = Owner.new(owner_params)

    respond_to do |format|
      if @owner.save
        format.html { redirect_to @owner, notice: 'Owner was successfully created.' }
        format.json { render :show, status: :created, location: @owner }
      else
        format.html { render :new }
        format.json { render json: @owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /owners/1
  # PATCH/PUT /owners/1.json
  def update
    respond_to do |format|
      if @owner.update(owner_params)
        format.html { redirect_to @owner, notice: 'Owner was successfully updated.' }
        format.json { render :show, status: :ok, location: @owner }
      else
        format.html { render :edit }
        format.json { render json: @owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /owners/1
  # DELETE /owners/1.json
  def destroy
    @owner.destroy
    respond_to do |format|
      format.html { redirect_to owners_url, notice: 'Owner was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_owner
      @owner = Owner.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def owner_params
      params.require(:owner).permit(:name, cats_attributes: [:id, :name, :birth_date, :picture])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/views/cats/_cats.html.erb
<ul>
<% @cats.each do |cat| %>
  <li>
    <%= image_tag cat.picture, class: "image-index" %>
    <%= cat.name %> 
    <span class='birth-date'>
      <%= cat.birth_date.strftime("%Y %d %b") if cat.birth_date %>
    </span>

    <span class="actions">
      <%= link_to "More Info", cat_path(cat) %> | 
      <%= link_to "Delete", cat_path(cat), method: :delete, data: {confirm: "Are you sure you wan't to delete the #{cat.name} "} %>
    </span>

    <strong>
      <% if cat.owner.nil? %>
        "No Owner"
      <% else %>
        <%= link_to "Has an owner", owner_path(cat.owner.id) %>
      <% end %>
    </strong>
  </li>
<% end %>
</ul>

app/views/cats/index.html.erb
<h1>Cats</h1>
<%= link_to "Add new cat", new_cat_path %>
<div class="cats-list">
  <%= render partial: 'cats' %> 
</div>

app/views/cats/new.html.erb
<h1>Adding LOLcat</h1>

<%= form_for @cat do |f| %>
  <% if @cat.errors.any? %>
    <div class="form-errors">
      <ul>
      <% @cat.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <p>
  <%= f.label :name %>
  <%= f.text_field :name, class: "name-field" %>
  </p>
  <p>
  <%= f.label :birth_date %>
  <%= f.date_field :birth_date, class: "date-field" %>
  </p>
  <p>
  <%= f.label :picture %>
  <%= f.file_field :picture %>
  </p>
  <p>
  <%= f.submit class: "submit-button" %>
  </p>
<% end %>

<%= link_to "Back", :back %>

app/views/cats/search.html.erb
<h1>Search for cat</h1>

<%= form_tag cats_search_path, method: :get do |f| %>
  <%= search_field_tag :name %>
  <%= submit_tag 'Search' %>
<% end %>
<br/>
<h2>Search results</h2>
<% if @cats.any? %>
<%= render partial: 'cats' %>
<% else %>
  Nothing found 
<% end %>

app/views/cats/show.html.erb
<h1><%= @cat.name %></h1>
<p>
<%= image_tag @cat.picture, width: 200 %>
</p>
<p>Is born: <%= @cat.birth_date.strftime("%Y %d %b") %></p>
<p>Owner:<br/>
<%= @cat.owner.nil? ? "No Owner" : @cat.owner.name %>
</p>

<p>
<%= link_to "Delete Image", delete_cat_image_path, method: :delete, data: {confirm: "Are you sure" } %>
<%= link_to "Back", :back %>

app/views/home/index.html.erb
<h1>Welcome to our LOLCats</h1>
<p>Welcome to our LOLCats </p>

<% @cats.each do |cat| %>
  <%= link_to (image_tag cat.picture, width: 200), cat_path(cat) %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lolcats</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<h1>Lolcats</h1>
<%= link_to "Homepage", root_path %> |
<%= link_to "Go to Cats", cats_path %> |
<%= link_to "Go to Owners", owners_path %>
<br/><br/>
<%= yield %>
</body>
</html>

app/views/owners/_form.html.erb
<%= form_for(@owner) do |f| %>
  <% if @owner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@owner.errors.count, "error") %> prohibited this owner from being saved:</h2>

      <ul>
      <% @owner.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <h2>Cats</h2>
    <%= f.fields_for :cats do |cf| %>
      <%= cf.label :name %>
      <%= cf.text_field :name %><br/>
      <%= cf.label :birth_date %>
      <%= cf.date_field :birth_date %><br/>
      <%= cf.label :picture %>
      <%= cf.file_field :picture %>
      <br/><br/>
    <% end %>
  </div>

    <%= f.submit %>
<% end %>
<br/><br/>

app/views/owners/edit.html.erb
<h1>Editing owner</h1>

<%= render 'form' %>

<%= link_to 'Show', @owner %> |
<%= link_to 'Back', owners_path %>

app/views/owners/index.html.erb
<h1>Listing owners</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @owners.each do |owner| %>
      <tr>
        <td><%= owner.name %></td>
        <td><%= link_to 'Show', owner %></td>
        <td><%= link_to 'Edit', edit_owner_path(owner) %></td>
        <td><%= link_to 'Destroy', owner, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Owner', new_owner_path %>

app/views/owners/new.html.erb
<h1>New owner</h1>

<%= render 'form' %>

<%= link_to 'Back', owners_path %>

app/views/owners/show.html.erb
<p id="notice"><%= notice %></p>

<p>

<h1> <%= @owner.name %></h1>
</p>
<p>

Owns:<br/>
<% if @owner.cats.any? %>
  <% @owner.cats.each do | cat|  %>
    <%= link_to cat.name, cat_path(cat) %>
  <% end %>
<% else %>
  Doesn't own cat
<% end %>
</p>

<%= link_to 'Edit', edit_owner_path(@owner) %> |
<%= link_to 'Back', owners_path %>